### ISSUE TITLE
Cannot run .jar file

### ISSUE THREAD

**Issue by microbially** [enasequence/ena-ftp-downloader#8]
This is similar to two already-closed issues, but the solutions offered to them don't apply to me.

I'm running Windows 8.1 and have installed Oracle JDK 12.0.1. After downloading the .jar file, double-clicking it does nothing, and if I try to run via the command line, I get the same message as reported in earlier issues: _Error: Could not find or load main class uk.ac.ebi.ena.downloader.gui.Main_

The .jar file in the .zip with runtime also does not run when it is double-clicked.

**Comment by suranjayathilaka** [comment]
Hi, 
Thanks for reporting this issue. Since JDK11 Oracle has separated the JavaFX libraries from the main JDK download.
I've added a Windows specific artifact which contains the required runtime libraries to the release, ena-file-downloader-v1.2.2-with-runtime-windows.rar, which you should be able to run.

Given the limited compatibility, we have decided to deprecate this project for the time-being. The current release artifacts will remain.
For bulk downloading files from the ENA, you could try the Python based convenience scripts at [enaBrowserTools](https://github.com/enasequence/enaBrowserTools/) as well.

My apologies for the inconvenience.
Suran
